### ISSUE TITLE
zeph-core tests fail without explicit --features env-vault after #3479

### ISSUE THREAD

**Issue by bug-ops** [bug-ops/zeph#3485]
## Description
After PR #3479 gated `EnvVaultProvider` behind the `env-vault` feature, running `cargo nextest run -p zeph-core` (without explicit feature flags) fails with a compilation error.

This regresses the developer workflow: running tests for a single crate without specifying feature flags is a common pattern documented in CLAUDE.md.

## Reproduction Steps
1. `cargo nextest run -p zeph-core` (no `--features` flag)

Observe:
```
error[E0432]: unresolved import `zeph_vault::EnvVaultProvider`
   --> crates/zeph-core/src/lib.rs:153:13
    |
153 |     pub use zeph_vault::EnvVaultProvider;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `EnvVaultProvider` in the root
```

## Expected Behavior
`cargo nextest run -p zeph-core` should compile and run tests without explicit feature flags.

## Actual Behavior
Compilation fails because `crates/zeph-core/src/lib.rs:153` is gated with `#[cfg(any(test, feature = "env-vault"))]`, which activates during test builds (`cfg(test)` is true), but the `zeph-vault/env-vault` feature is not enabled unless explicitly passed.

## Root Cause
`#[cfg(any(test, feature = "env-vault"))]` in `zeph-core/src/lib.rs` uses the `test` cfg to include the `pub use zeph_vault::EnvVaultProvider;` re-export in test builds. However, `zeph-vault` only exports `EnvVaultProvider` when `zeph-vault/env-vault` feature is active. Since `zeph-core`'s `env-vault` feature (`= ["zeph-vault/env-vault"]`) is not in `zeph-core`'s `[features] default`, running tests without explicit `--features env-vault` leaves `zeph-vault::EnvVaultProvider` invisible.

## Fix Options
1. **Preferred**: Change `#[cfg(any(test, feature = "env-vault"))]` to `#[cfg(feature = "env-vault")]` — require explicit feature for test use too. Tests that need `EnvVaultProvider` must run with `--features env-vault`.
2. **Alternative**: Add `env-vault` to `zeph-core`'s default features list.

## Environment
- Version: 0.20.0 (HEAD 55044a20)
- Introduced by: PR #3479
- Workaround: `cargo nextest run --config-file .github/nextest.toml -p zeph-core --features env-vault`

## Logs / Evidence
```
error[E0432]: unresolved import `zeph_vault::EnvVaultProvider`
   --> crates/zeph-core/src/lib.rs:153:13
153 |     pub use zeph_vault::EnvVaultProvider;
hint: a similar name exists in the module - pub use zeph_vault::VaultProvider;
```
Full build passes: `cargo nextest run --workspace --features full` → 8962/8962 tests PASS.
